Feat: routeSystem lazy 기능 및 redirect 기능 추가
thesoncriel/jordy pull request #46
Opened 2023-02-03 06:44 UTC by chkim116

## Updates 

- lazy와 redirect 기능을 추가합니다.
  - 기본은 false이고, `useRoutesSystem()` 사용 시 기본 값을 true로 변경 가능합니다.

## Others 

- redirect를 추가하고 생각 해보니, 조건에 따른 redirect가 있으면 좋겠다 생각이 들었습니다. 그렇지만 이 부분은 컴포넌트 자체에서 맡기는 게 더 나을 듯 하네요. 조건문까지 추가하려다 보면 너무 비대해 지지 않을까 싶습니다.
- 테스트 케이스 추가

2023-02-07 01:27 UTC, thesoncriel commented
> 조건에 따른 redirect가 있으면 좋겠다 생각이 들었습니다.

오우! 이게 어떤 상황에 따라 생각이 드신건지, 이따가 공유 주시면 좋을 것 같습니다~~ 👍

2023-02-07 02:29 UTC, thesoncriel commented
구두로 말씀드린 내용을 정리 해 둡니다~
- 이번에 추가된 `lazy` 기능은 본래 취지인 코드 분할을 할 수 없습니다.
  - 따라서 lazy 기능은 정리가 필요합니다.
- 한편, fallback 은 현재 suspense 에서 fragment 로 지정되어 변경이 어렵게 되어 있는 부분을 보완 해 주는 것이기에 필요합니다.

하여, 해당 내용 수정을 부탁드리겠습니다! 🙇‍♂️

2023-02-07 02:30 UTC, thesoncriel requested changes

2023-02-21 07:43 UTC, chkim116 commented
> > 조건에 따른 redirect가 있으면 좋겠다 생각이 들었습니다.
> 
> 오우! 이게 어떤 상황에 따라 생각이 드신건지, 이따가 공유 주시면 좋을 것 같습니다~~ 👍

예를들면 유저 권한이 없을 시 경우입니다. 지금 지원하는 건 특정 path 접속 시 redirect 하는 기능인데 유저 권한 여부에 따라 redirect 하거나 redirect 하지 않는 조건문도 내부적으로 구현할까 생각했습니다~

2023-02-21 07:44 UTC, chkim116 commented
> 구두로 말씀드린 내용을 정리 해 둡니다~
> 
> * 이번에 추가된 `lazy` 기능은 본래 취지인 코드 분할을 할 수 없습니다.
>   
>   * 따라서 lazy 기능은 정리가 필요합니다.
> * 한편, fallback 은 현재 suspense 에서 fragment 로 지정되어 변경이 어렵게 되어 있는 부분을 보완 해 주는 것이기에 필요합니다.
> 
> 하여, 해당 내용 수정을 부탁드리겠습니다! 🙇‍♂️

넵 감사합니다!

2023-02-21 08:06 UTC, chkim116 commented
[96208cf](https://github.com/thesoncriel/jordy/pull/46/commits/96208cf2b856e5d714df6e1ff3076bb865e74b79) lazy 제거하였습니다!

2023-02-21 08:21 UTC, thesoncriel approved these changes
확인했습니다~!
의견 반영 감사드려요~!
구두로 의견 드린 내용을 정리해 놓았으니 확인하시고 반영 부탁드리겠습니다~! 👍

2023-02-21 08:21 UTC, thesoncriel commented on packages/route-system/useRouteSystem.tsx
>            <Element />
구두로도 설명드렸듯이 fallback 설정이 비어있다면, Fragment 나 null 로 채워주되 Suspense 는 항상 감싸 주시는게 좋을 듯 합니다!

2023-05-23 08:38 UTC, chkim116 commented
close 합니다.

사유 - #53

2023-05-23 08:38 UTC, closed without merging